### ISSUE TITLE
In Settings, Notification toggle isnt work properly (See Video)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Gifty-Funds#46]
https://images.zenhubusercontent.com/441429721/65bb4bd7-8a45-4314-b011-5428b1e3810b/in_settings__notification_toggle_isnt_work_properly__see_video_.mp4

**Comment by Adnan46** [comment]
ye abhi alpha hai, jesa ap chah rhe wo backend integrate krne ke bd aesa work krega
